export const UIConstants = {
  REVIEW_CONTENT_LABEL: 'Ваш отзыв',
  REVIEW_CONTENT_PLACEHOLDER: 'Поделитесь своими мыслями об этом стихотворении...',
  RATING_LABEL: 'Оценка',
  SUBMIT_BUTTON: 'Опубликовать отзыв',
  SUBMITTING_BUTTON: 'Публикация...',
  CANCEL_BUTTON: 'Отмена',
  REVIEWS_TITLE: 'Отзывы',
  NO_REVIEWS_MESSAGE: 'Пока нет отзывов. Будьте первым!',
  REVIEW_SUCCESS_MESSAGE: 'Отзыв успешно опубликован',
  REVIEW_ERROR_MESSAGE: 'Ошибка при публикации отзыва',
  REPORT_BUTTON: 'Пожаловаться',
  DELETE_BUTTON: 'Удалить',
  EDIT_BUTTON: 'Редактировать',
  RATING_STARS_LABEL: 'из 5 звезд',
} as const;
