export const RoutePath = {
  HOME: {
    path: '/',
    name: 'Главная',
    type: 'public',
    role: 'all',
  },
  ABOUT: {
    path: '/about',
    name: 'about',
    type: 'public',
    role: 'all',
  },
  DASHBOARD: {
    path: '/dashboard',
    name: 'dashboard',
    type: 'private',
    role: 'admin',
  },
  LOGIN: {
    path: '/auth',
    name: 'Войти',
    type: 'public',
    role: 'all',
  },
  POEMS_LIST: {
    path: '/poems',
    name: 'Стихи',
    type: 'public',
    role: 'all',
  },
  POEM_DETAIL: {
    path: '/poems/[id]',
    name: 'poemDetail',
    type: 'public',
    role: 'all',
  },
  PROFILE: {
    path: '/profile',
    name: 'Профиль',
    type: 'private',
    role: 'subscriber',
  },
  PROFILE_SETTINGS: {
    path: '/profile',
    name: 'profileSettings',
    type: 'private',
    role: 'subscriber',
  },
  PROFILE_MY_POEMS: {
    path: '/profile/my-poems',
    name: 'profileMyPoems',
    type: 'private',
    role: 'author',
  },
  PROFILE_ADD_POEM: {
    path: '/profile/add-poem',
    name: 'profileAddPoem',
    type: 'private',
    role: 'author',
  },
  PROFILE_EDIT_POEM: {
    path: '/profile/edit-poem',
    name: 'profileEditPoem',
    type: 'private',
    role: 'author',
  },
  CATEGORY: {
    path: '/poems/category/[slug]',
    name: 'category',
    type: 'public',
    role: 'all',
  },
  TAG: {
    path: '/tags/[slug]',
    name: 'tag',
    type: 'public',
    role: 'all',
  },
  SEARCH: {
    path: '/search',
    name: 'search',
    type: 'public',
    role: 'all',
  },
  ADMIN_CATEGORIES: {
    path: '/admin/categories',
    name: 'adminCategories',
    type: 'private',
    role: 'moderator',
  },
  ADMIN_USERS: {
    path: '/admin/users',
    name: 'adminUsers',
    type: 'private',
    role: 'admin',
  },
};
