export const UIConstants = {
  COMMENT_CONTENT_LABEL: 'Ваш комментарий',
  COMMENT_CONTENT_PLACEHOLDER: 'Поделитесь своими мыслями...',
  SUBMIT_BUTTON: 'Отправить комментарий',
  SUBMITTING_BUTTON: 'Отправка...',
  CANCEL_BUTTON: 'Отмена',
  COMMENTS_TITLE: 'Комментарии',
  NO_COMMENTS_MESSAGE: 'Пока нет комментариев. Будьте первым!',
  COMMENT_SUCCESS_MESSAGE: 'Комментарий успешно добавлен',
  COMMENT_ERROR_MESSAGE: 'Ошибка при добавлении комментария',
  COMMENT_DELETE_SUCCESS_MESSAGE: 'Комментарий успешно удален',
  COMMENT_UPDATE_SUCCESS_MESSAGE: 'Комментарий успешно обновлен',
  COMMENT_UPDATE_ERROR_MESSAGE: 'Ошибка при обновлении комментария',
  COMMENT_DELETE_ERROR_MESSAGE: 'Ошибка при удалении комментария',
  COMMENT_WORK_ERROR_MESSAGE: 'Произошла ошибка при работе с комментарием',
  COMMENT_SUBMIT_ERROR_MESSAGE: 'Произошла ошибка при отправке комментария',
  REPORT_BUTTON: 'Пожаловаться',
  DELETE_BUTTON: 'Удалить',
  EDIT_BUTTON: 'Редактировать',
} as const;
